# Generated by Django 5.0.2 on 2024-04-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor_name',
        ),
        migrations.DeleteModel(
            name='HistoricalPerformance',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
